apiVersion: v1
kind: Service
metadata:
  name: banknamingserver
  labels:
    app: banknamingserver
    service: banknamingserver
spec:
  type: LoadBalancer
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
  selector:
    service: banknamingserver